### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by chcs71** [TomDotBat/AutoToot#2]
Hello, I've never coded anything before and I'm trying to compile this mod, but it keeps showing "The type or namespace namecould not be found. Are you missing a using directive or an assembly reference?" for GameController and PointSceneController, how do I fix this? Sorry if this isn't an issue related to the mod itself, and if that's the case, I'll delete this and try to solve it on my own.

**Comment by TomDotBat** [comment]
You'll need to use [NStrip](https://github.com/BepInEx/NStrip) on Assembly-CSharp.dll and reference the output.
There's no need to compile the mod yourself unless you're making changes to it, you can download a pre-compiled release [here](https://github.com/TomDotBat/AutoToot/releases).
